name: Build

on:
  push:
    branches: 
      - master
    paths:
      - FastMM4.pas
      - FastMM4Messages.pas
      - FastMM4Options.inc

  workflow_dispatch:

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@latest

      - name: Install Free Pascal
        run: |
          sudo apt-get update
          sudo apt-get install -y fpc

      - name: Compile a simple demo in ObjFPC mode
        run: cd $GITHUB_WORKSPACE/Tests/Simple && fpc -B -MObjFPC -Tlinux -Px86_64 -O4 SimpleTest.dpr

      - name: Compile a simple demo in Delphi mode
        run: cd $GITHUB_WORKSPACE/Tests/Simple && fpc -B -Mdelphi -Tlinux -Px86_64 -O4 SimpleTest.dpr

      - name: Compile with various defined options
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          fpc -B -Mdelphi -Tlinux -Px86_64 -dDEBUG -g -O- SimpleTest.dpr

      - name: Compile with -dDEBUG -g -dFullDebugMode
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          fpc -B -Mdelphi -Tlinux -Px86_64 -dDEBUG -g -dFullDebugMode -O- SimpleTest.dpr

      - name: Compile with -dFullDebugMode
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          fpc -B -Mdelphi -Tlinux -Px86_64 -dFullDebugMode -O4 SimpleTest.dpr

      - name: Compile with -dAlign16Bytes
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          fpc -B -Mdelphi -Tlinux -Px86_64 -dAlign16Bytes -O4 SimpleTest.dpr

      - name: Compile with -dAlign32Bytes
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          fpc -B -Mdelphi -Tlinux -Px86_64 -dAlign32Bytes -O4 SimpleTest.dpr

      - name: Compile with -dDontUseCustomFixedSizeMoveRoutines
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          fpc -B -Mdelphi -Tlinux -Px86_64 -dDontUseCustomFixedSizeMoveRoutines -O4 SimpleTest.dpr

      - name: Compile with -dDontUseCustomVariableSizeMoveRoutines
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          fpc -B -Mdelphi -Tlinux -Px86_64 -dDontUseCustomVariableSizeMoveRoutines -O4 SimpleTest.dpr

      - name: Compile with -dForceSingleThreaded
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          fpc -B -Mdelphi -Tlinux -Px86_64 -dForceSingleThreaded -O4 SimpleTest.dpr

      - name: Compile with -dDisablePauseAndSwitchToThread
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          fpc -B -Mdelphi -Tlinux -Px86_64 -dDisablePauseAndSwitchToThread -O4 SimpleTest.dpr

      - name: Compile with -dDontUseSmallBlocksLockedCriticalSection
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          fpc -B -Mdelphi -Tlinux -Px86_64 -dDontUseSmallBlocksLockedCriticalSection -O4 SimpleTest.dpr

      - name: Compile with -dDontUseMediumBlocksLockedCriticalSection
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          fpc -B -Mdelphi -Tlinux -Px86_64 -dDontUseMediumBlocksLockedCriticalSection -O4 SimpleTest.dpr

      - name: Compile with -dDontUseLargeBlocksLockedCriticalSection
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          fpc -B -Mdelphi -Tlinux -Px86_64 -dDontUseLargeBlocksLockedCriticalSection -O4 SimpleTest.dpr

      - name: Compile with -dDontUseASMVersion
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          fpc -B -Mdelphi -Tlinux -Px86_64 -dDontUseASMVersion -O4 SimpleTest.dpr

      - name: Compile with -dDontUseASMVersion
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          fpc -B -Mdelphi -Tlinux -Px86_64 -dDontUseASMVersion -O4 SimpleTest.dpr

      - name: Compile with -dDisableMemoryLeakReporting
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          fpc -B -Mdelphi -Tlinux -Px86_64 -dDisableMemoryLeakReporting -O4 SimpleTest.dpr

      - name: Compile with -dRequireIDEPresenceForLeakReporting
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          fpc -B -Mdelphi -Tlinux -Px86_64 -dRequireIDEPresenceForLeakReporting -O4 SimpleTest.dpr


